name: parsing
favicon: null
layout_spectrum: 0.5096503144595772
typography_spectrum: 0.9802079519722611
title: parsing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2287397482432425
  lightness: 0.125
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
