name: parsing
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37883
title: parsing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2e7e5'
    - '#8f8b8c'
    - '#6a686b'
    - '#29282d'
    - '#cbc2c3'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
